from glob import glob
import pyfiglet
import time

def main():
    pyfiglet.print_figlet("Indexer")
    start = time.process_time()
    print("now indexing files.")
    files = glob("*.md") + glob("**/*.md")
    print("indexed files.")
    print("now writing files.")
    with open("page_index.md", "w") as file:
        file.truncate(0) # reset it
        file.write("# Page Index\n\n")
        file.write("*automatically generated by a python script, if there are issues please report on our github*\n\n")
        for markdown in files:
            if markdown.startswith("build"):
                continue

            file.write(f"- [{markdown}]({markdown[:len(markdown) - 3]})\n")
    end = time.process_time()
    print(f"finished in {(end - start) * 10**3}ms.")

if __name__ == "__main__":
    main()