from glob import glob

def main():
    files = glob("*.md") + glob("**/*.md")
    with open("page_index.md", "w") as file:
        file.truncate(0) # reset it
        file.write("# Page Index\n\n")
        file.write("*automatically generated by a python script, if there are issues please report on our github*\n")
        for markdown in files:
            if markdown.startswith("build"):
                continue

            file.write(f"- [{markdown}]({markdown})\n")

if __name__ == "__main__":
    main()